//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class indrayanimilkEntities : DbContext
    {
        public indrayanimilkEntities()
            : base("name=indrayanimilkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TablPartner> TablPartners { get; set; }
        public DbSet<Tbl_Gallary> Tbl_Gallary { get; set; }
        public DbSet<TblAboutDairy> TblAboutDairies { get; set; }
        public DbSet<TblAboutDirector> TblAboutDirectors { get; set; }
        public DbSet<TblAdmin> TblAdmins { get; set; }
        public DbSet<TblContact> TblContacts { get; set; }
        public DbSet<TblDealer> TblDealers { get; set; }
        public DbSet<TblFranchise> TblFranchises { get; set; }
        public DbSet<TblInfrastructure> TblInfrastructures { get; set; }
        public DbSet<TblProduct> TblProducts { get; set; }
        public DbSet<TblProductPackage> TblProductPackages { get; set; }
        public DbSet<TblCareer> TblCareers { get; set; }
        public DbSet<TblCountry> TblCountries { get; set; }
        public DbSet<TblState> TblStates { get; set; }
        public DbSet<TblCity> TblCities { get; set; }
    }
}
