//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablPartner
    {
        public int part_id { get; set; }
        public string part_name { get; set; }
        public string part_number { get; set; }
        public string part_email { get; set; }
        public string part_company { get; set; }
        public string part_designation { get; set; }
        public string part_message { get; set; }
    }
}
