//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAboutDirector
    {
        public int dir_id { get; set; }
        public string dir_name { get; set; }
        public string dir_content { get; set; }
        public string dir_image { get; set; }
    }
}
