//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCareer
    {
        public int job_id { get; set; }
        public string job_title { get; set; }
        public string job_expereince { get; set; }
        public string job_description { get; set; }
        public string job_salary { get; set; }
        public string job_date_post { get; set; }
        public string job_last_date { get; set; }
    }
}
