//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDealer
    {
        public int dealer_id { get; set; }
        public string dealer_name { get; set; }
        public string dealer_number { get; set; }
        public string dealer_email { get; set; }
        public string dealer_address { get; set; }
        public string dealer_pin { get; set; }
        public string dealer_country { get; set; }
        public string dealer_state { get; set; }
        public string dealer_city { get; set; }
        public string dealer_company { get; set; }
        public string dealer_fax { get; set; }
        public string dealer_description { get; set; }
    }
}
