//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFranchise
    {
        public int fran_id { get; set; }
        public string fran_name { get; set; }
        public string fran_number { get; set; }
        public string fran_email { get; set; }
        public string fran_address { get; set; }
        public string fran_pin { get; set; }
        public string fran_country { get; set; }
        public string fran_state { get; set; }
        public string fran_city { get; set; }
        public string fran_company { get; set; }
        public string fran_fax { get; set; }
        public string fran_description { get; set; }
    }
}
