//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace talekarmilk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInfrastructure
    {
        public int infra_id { get; set; }
        public string infra_title { get; set; }
        public string infra_content { get; set; }
        public string infra_image { get; set; }
    }
}
